name: Release App & Deploy Web

on:
  push:
    tags: [ "v*" ]

permissions:
  contents: write

jobs:
  build-tauri:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      # Hapus Rust Cache untuk memastikan tidak ada sisa file lama yang menyebabkan konflik
      - name: Build Portable Executable
        env:
          CARGO_NET_RETRY: "10"
          CARGO_NET_TIMEOUT: "300"
        run: |
          cd src-tauri
          # Perintah ini menghapus semua artefak kompilasi lama
          cargo clean
          # Membangun ulang dari nol
          cargo build --release
        
      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          files: |
            src-tauri/target/release/app.exe

  deploy-web:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          publish_dir: ./www